version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: closuretable
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      DB_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    restart: always
    depends_on:
      - postgres
